### ISSUE TITLE
bug: TMI docs are currently nested under Kraken

### ISSUE THREAD

**Issue by iProdigy** [twitch4j/twitch4j.github.io#2]
### Prerequisites
* [x] If this is a question/suggestion, I have already considered discuss it on [Discord Server](https://discord.gg/FQ5vgW3)
* [x] This issue specifically has something to do with Twitch4J
* [x] I have attempted to [look for similar issues](https://github.com/twitch4j/twitch4j/issues) already

### Description
API - TMI is currently nested under API - Kraken when it should be its own category

### Steps to Reproduce
Expand the docs for API - Kraken

![chrome_qFsyiB7GSH](https://user-images.githubusercontent.com/8106344/106365155-42154100-62f9-11eb-89bb-3669e29852ce.png)

**Comment by stachu540** [comment]
Change parent int front matter will resolves this issue
