### ISSUE TITLE
UI/UX: Navigation buttons are too hard to press due to small bounding boxes

### ISSUE THREAD

**Issue by iProdigy** [twitch4j/twitch4j.github.io#3]
### Prerequisites
* [x] If this is a question/suggestion, I have already considered discuss it on [Discord Server](https://discord.gg/FQ5vgW3)
* [x] This issue specifically has something to do with Twitch4J
* [x] I have attempted to [look for similar issues](https://github.com/twitch4j/twitch4j/issues) already

### Description
Clicking on a button like this does not expand the child docs or redirect to the page (i.e., nothing happens)
![chrome_w4S229UtF8](https://user-images.githubusercontent.com/8106344/106365269-10e94080-62fa-11eb-9cea-e461ce85233e.png)

### Cause
The href is only applied to the text:
![chrome_DgFE1UXSvb](https://user-images.githubusercontent.com/8106344/106365278-22324d00-62fa-11eb-981d-f8087f8cd534.png)

### Related Problem
The arrow to expand the children pages is too small to reliably click:
![chrome_k8HNoGyie8](https://user-images.githubusercontent.com/8106344/106365312-573e9f80-62fa-11eb-8e60-17101944d224.png)

**Comment by stachu540** [comment]
Will do in the next week or tomorrow.

**Comment by PhilippHeuer** [comment]
Fixed this one, not the nicest solution but quick and works.
