### ISSUE TITLE
Search Bar index overflowing data into front-end side

### ISSUE THREAD

**Issue by stachu540** [twitch4j/twitch4j.github.io#4]
### Description
The current search bar resolves results in one index which are overflowing web browser. The solution is pagination results.  Only from the client-side. But in near future we could implement search engine using ElasticSearch for bot solutions. 

### To Do List
- [ ] Strict results into pagination - ex. 5 results on search bar, 25 in website.
- [ ] Refill documentation content with tags - needs for better perform searching content
- [ ] Enhance search UI index

**Comment by iProdigy** [comment]
I think this was resolved by #30
